// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/gin-gonic/gin"
	"github.com/lcsin/webook/internal/handler"
	"github.com/lcsin/webook/internal/repository"
	"github.com/lcsin/webook/internal/repository/cache"
	"github.com/lcsin/webook/internal/repository/dao"
	"github.com/lcsin/webook/internal/service"
	"github.com/lcsin/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := handler.InitMiddlewares()
	db := ioc.InitDB()
	iUserDAO := dao.NewUserDAO(db)
	cmdable := ioc.InitRedis()
	iUserCache := cache.NewUserCache(cmdable)
	iUserRepository := repository.NewUserRepository(iUserDAO, iUserCache)
	iUserService := service.NewUserService(iUserRepository)
	userHandler := handler.NewUserHandler(iUserService)
	v2 := handler.InitHandlers(userHandler)
	engine := ioc.InitRouter(v, v2)
	return engine
}
