// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/lcsin/webook/internal/handler"
	"github.com/lcsin/webook/internal/repository"
	"github.com/lcsin/webook/internal/repository/cache"
	"github.com/lcsin/webook/internal/repository/dao"
	"github.com/lcsin/webook/internal/service"
	"github.com/lcsin/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := handler.InitMiddlewares()
	db := ioc.InitDB()
	iUserDAO := dao.NewUserDAO(db)
	cmdable := ioc.InitRedis()
	iUserCache := cache.NewUserCache(cmdable)
	iUserRepository := repository.NewUserRepository(iUserDAO, iUserCache)
	iUserService := service.NewUserService(iUserRepository)
	userHandler := handler.NewUserHandler(iUserService)
	iArticleDAO := dao.NewArticleDAO(db)
	iArticleRepository := repository.NewArticleRepository(iArticleDAO, iUserDAO)
	iArticleService := service.NewArticleService(iArticleRepository)
	articleHandler := handler.NewArticleHandler(iArticleService)
	v2 := handler.InitHandlers(userHandler, articleHandler)
	engine := ioc.InitRouter(v, v2)
	return engine
}

func InitTestArticleHandler() *handler.ArticleHandler {
	db := ioc.InitTestDB()
	iArticleDAO := dao.NewArticleDAO(db)
	iUserDAO := dao.NewUserDAO(db)
	iArticleRepository := repository.NewArticleRepository(iArticleDAO, iUserDAO)
	iArticleService := service.NewArticleService(iArticleRepository)
	articleHandler := handler.NewArticleHandler(iArticleService)
	return articleHandler
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitRouter, handler.InitHandlers, handler.InitMiddlewares)

var userHandlerProvider = wire.NewSet(dao.NewUserDAO, cache.NewUserCache, repository.NewUserRepository, service.NewUserService, handler.NewUserHandler)

var articleHandlerProvider = wire.NewSet(dao.NewArticleDAO, repository.NewArticleRepository, service.NewArticleService, handler.NewArticleHandler)
