// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/lcsin/glib/ginlayout/internal/handler"
	"github.com/lcsin/glib/ginlayout/internal/repository"
	"github.com/lcsin/glib/ginlayout/internal/repository/dao"
	"github.com/lcsin/glib/ginlayout/internal/service"
	"github.com/lcsin/glib/ginlayout/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := handler.InitMiddlewares()
	db := ioc.InitDB()
	iBookDAO := dao.NewBookDAO(db)
	iBookRepository := repository.NewBookRepository(iBookDAO)
	iBookService := service.NewBookService(iBookRepository)
	bookHandler := handler.NewBookHandler(iBookService)
	v2 := handler.InitHandlers(bookHandler)
	engine := ioc.InitRouter(v, v2)
	return engine
}

// wire.go:

// 第三方依赖注入
var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitRouter, handler.InitHandlers, handler.InitMiddlewares)

// bookHandlerProvider 依赖注入
var bookHandlerProvider = wire.NewSet(dao.NewBookDAO, repository.NewBookRepository, service.NewBookService, handler.NewBookHandler)
