// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"ginlayout/internal/handler"
	"ginlayout/internal/repository"
	"ginlayout/internal/repository/cache"
	"ginlayout/internal/repository/dao"
	"ginlayout/internal/service"
	"ginlayout/ioc"

	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := handler.InitMiddlewares()
	db := ioc.InitDB()
	iHelloDAO := dao.NewHelloDAO(db)
	cmdable := ioc.InitRedis()
	iHelloCache := cache.NewHelloCache(cmdable)
	iHelloRepository := repository.NewHelloRepository(iHelloDAO, iHelloCache)
	iHelloService := service.NewHelloService(iHelloRepository)
	helloHandler := handler.NewHelloHandler(iHelloService)
	v2 := handler.InitHandlers(helloHandler)
	engine := ioc.InitRouter(v, v2)
	return engine
}
