app:
  name: "app_name"
  port: "8080"
mysql:
  dns: "root:root@tcp(192.168.193.240:3306)/pandora?charset=utf8mb4&parseTime=True"
redis:
  addr: "localhost:16379"
  passwd: ""
jwt:
  key: "308eef61a95de468d3477ca9b347b6e0"
